### ISSUE TITLE
Protocol getter matches using 'https' instead of 'https:' causes errors when making ssl requests.

### ISSUE THREAD

**Issue by sswayney** [ZEXSM/node-scc-config#11]
https://github.com/ZEXSM/node-scc-config/blob/c7a4f9349937a004c6d45b040600369cf84ea2c8/src/spring-cloud-config-client.ts#L28

The protocol getter in SpringCloudConfigClient class matches the url.protocol for 'https' when the value is 'https:' when using an https endpoint.  The error:

Protocol "https:" not supported. Expected "http:"

Thank you. :)

**Comment by ZEXSM** [comment]
Hi! Thanks for your input
I suggest making a check using startWith

`if (this.url.protocol.startsWith('https'))`.

**Comment by sswayney** [comment]
Thanks. Great idea. Updated PR.
